# ============================================
# application.properties — Common Settings
# Shared by ALL team members (Arch + Windows)
# ============================================

spring.application.name=nexus

# JPA Common Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Colombo

# Email (Gmail SMTP) — shared by all
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giftora033@gmail.com
spring.mail.password=ntib evaa kouu ehxb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
<<<<<<< HEAD
=======
spring.profiles.active=windows
>>>>>>> 9baf4b97079b34b82fa7c346aec28ba39936c30a

# ── Server ───────────────────────────────────
server.port=8080


# ── Hibernate Dialect ─────────────────────────
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── Jackson JSON ──────────────────────────────
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE