# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "Giftora — Personalized Gift Box Marketplace"
remote_theme: cepdnaclk/eYY-project-theme
description: "A multi-vendor platform for customizing, assembling, and tracking personalized gift boxes."
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
